name: Test with Jest
on:
  push
jobs:
  test_repository:
    name: Test with Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Test
        run: npm run test